// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"aicode/internal/controller"
	"aicode/internal/mapper"
	"aicode/internal/router"
	"aicode/internal/service/impl"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序（此函数会被wire生成）
func InitializeApp() (*App, error) {
	healthController := controller.NewHealthController()
	config := MustProvideConfig()
	db := MustProvideDB(config)
	userMapper := mapper.NewUserMapper(db)
	userService := impl.NewUserService(userMapper)
	userController := controller.NewUserController(userService)
	engine := router.SetupRouter(healthController, userController)
	app := &App{
		Router:           engine,
		UserController:   userController,
		HealthController: healthController,
	}
	return app, nil
}

// wire.go:

// App 应用程序结构体，包含所有需要的组件
type App struct {
	Router           *gin.Engine
	UserController   *controller.UserController
	HealthController *controller.HealthController
}

// wireSet 定义所有的provider集合
var wireSet = wire.NewSet(
	MustProvideConfig,
	MustProvideDB, router.SetupRouter, mapper.NewUserMapper, impl.NewUserService, controller.NewUserController, controller.NewHealthController,
)
